### ISSUE TITLE
ComfyUI started but the page crashes the browser

### ISSUE THREAD

**Issue by huchenlei** [Amorano/Jovimetrix#51] opened 2024-08-28 15:42 UTC
Original issue: https://github.com/comfyanonymous/ComfyUI/issues/4657

### Expected Behavior

start ui normally

### Actual Behavior

I started it via vscode and got the log
`
Starting server
To see the GUI go to: http://127.0.0.1:8188
`

I tried with chrome and only the menu flashed for 1 frame then the browser said the page crashed with STATUS_BREAKPOINT. I also tried edge and it did not work.

I'm wondering if it's my workflow that caused this. Is there anyway I can replace the startup workflow in comfyUI to try if it works out?

### Steps to Reproduce

I did not find the cause

### Debug Logs

```


### Other

_No response_

**Comment by Amorano** [comment] 2024-08-28 16:06
Sorry, not sure what this has to do with me?

That sounds like a local problem for you. What browser? What version? I have no issues in Firefox, Chrome or Opera.

**Comment by Amorano** [comment] 2024-08-28 16:08
That isnt a Jovimetrix problem, that is a problem in ClipText not being able to decode the unicode emoji.

**Comment by christian-byrne** [comment] 2024-09-03 00:11
I can reproduce on Chrome, Edge, Opera with no other custom nodes installed. 

System:

```
Linux cbyrne 6.5.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:10:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Google Chrome 128.0.6613.84 
Microsoft Edge 128.0.2739.42 
Opera 113.0.5230.32

ComfyUI d043997
```
Reproduction steps:
1. Install Jovimetrix nodes
2. Start ComfyUI process
3. Open browser to localhost:8188, with default workflow
4. Sometimes necessary to refresh 1-3 times
5. Get error code `SIGILL` in browser

From sys log:

```
kernel: [28960.732254] traps: chrome[1078548] trap invalid opcode ip:5f004b413408 sp:7ffc0ef99a10 error:0 in chrome[5f0049190000+b6b9000]
```

**Comment by Amorano** [comment] 2024-09-03 02:05
> I can reproduce on Chrome, Edge, Opera with no other custom nodes installed.
> 
> System:
> 
> ```
> Linux cbyrne 6.5.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:10:09 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> 
> Google Chrome 128.0.6613.84 
> Microsoft Edge 128.0.2739.42 
> Opera 113.0.5230.32
> 
> ComfyUI d043997
> ```
> 
> Reproduction steps:
> 
>     1. Install Jovimetrix nodes
> 
>     2. Start ComfyUI process
> 
>     3. Open browser to localhost:8188, with default workflow
> 
>     4. Sometimes necessary to refresh 1-3 times
> 
>     5. Get error code `SIGILL` in browser
> 
> 
> From sys log:
> 
> ```
> kernel: [28960.732254] traps: chrome[1078548] trap invalid opcode ip:5f004b413408 sp:7ffc0ef99a10 error:0 in chrome[5f0049190000+b6b9000]
> ```

Is specifically a Linux issue? Or is this reproducible across Windows and Mac?

I am going to go out on a limb and guess its something like the GLSL or the Streaming Device(s). Perhaps trying to ignore those nodes will sus out more information. 

I personally do not use Linux boxes in any setup other than to render, which is headless and removes the device(s). That is the first thing I can think of that may be the issue.

**Comment by Amorano** [comment] 2024-09-03 02:06
https://answers.microsoft.com/en-us/microsoftedge/forum/all/this-page-is-having-a-problem-error-code-sigill/e2a09ac0-f243-40cb-a235-41abb2148f07

could also just be an Ubuntu problem?

**Comment by christian-byrne** [comment] 2024-09-03 06:49
> https://answers.microsoft.com/en-us/microsoftedge/forum/all/this-page-is-having-a-problem-error-code-sigill/e2a09ac0-f243-40cb-a235-41abb2148f07
> 
> could also just be an Ubuntu problem?

Yes, I think maybe just Linux chromium.

It's hard to debug since browser process is killed. I think there's a chromium bug that causes the illegal CPU instruction and the bug is being triggered by Jovimetrix frontend/server code somehow. It might be solved by future browser updates.

**Comment by JS1989git** [comment] 2024-09-04 05:31
I have the same problem. I just run windows. It happens across all chromium based browsers. I'm still able to load into the ui in firefox though.

What's super frustrating is not being sure what caused it. I guess just some kind of windows update? Because I didn't change anything else. 

At first I thought it was the browser getting overloaded/a memory leak from having been doing a lot of video stuff lately and sometimes having the ui freeze (needing to refresh) when I'd have like 20 or 30 videos playing in the ui and had to hit "undo." It would lag loading them all back in and I was thinking that's what was causing the issue. That the only thing that I've been doing differently/the only behavior I've noticed a difference in that might have been the cause.

Idk, all I know is that I can hope I get my isolated build up soon. These random bugs that aren't your fault or in your control get more catastrophic the more you're trying to do in the ui.

**Comment by Sheldongg** [comment] 2024-09-04 05:46
same problem,deal by delete Jovimetric

**Comment by Amorano** [comment] 2024-09-04 14:20
I filed a bug report for Chromium, with the crashes that I got using Chrome on Linux; I cant make it crash my windows version, which is maybe why I didn't see this there.

I am not getting any dump of the problem, but I did send whatever bug dump it does for the crash tool.

if you surf into:

chrome://crashes/

You can send the error(s) reports to google and follow up. I suggest everyone do this while I try to find which specific thing is causing the problem.

Sorry for the drag on the workflow!

**Comment by Amorano** [comment] 2024-09-04 14:29
> Idk, all I know is that I can hope I get my isolated build up soon. These random bugs that aren't your fault or in your control get more catastrophic the more you're trying to do in the ui.

Thanks for the hint about the increase through UI use. I have been able to eliminate all the actual nodes and python side from being the problem. This is 100% a problem someplace in the JS/Routes.

**Comment by Amorano** [comment] 2024-09-04 15:05
so, uh....

`import * as util_config from '../util/util_config.js'`
-->
`import { setting_store } from '../util/util_config.js'`


and it works fine. Zero clue why that is a problem, but it is resolved in the latest push.

Please let me know if that clears it up for you!

**Comment by JS1989git** [comment] 2024-09-04 15:18
> so, uh....
> 
> `import * as util_config from '../util/util_config.js'` --> `import { setting_store } from '../util/util_config.js'`
> 
> and it works fine. Zero clue why that is a problem, but it is resolved in the latest push.
> 
> Please let me know if that clears it up for you!

Cool, thanks. Happen to know if it's still compatible with the pre big August 15th update? If not I can always just edit the code myself (I think) for my static build. Might do that actually. lol.

**Comment by Amorano** [comment] 2024-09-04 15:34
> > so, uh....
> > `import * as util_config from '../util/util_config.js'` --> `import { setting_store } from '../util/util_config.js'`
> > and it works fine. Zero clue why that is a problem, but it is resolved in the latest push.
> > Please let me know if that clears it up for you!
> 
> Cool, thanks. Happen to know if it's still compatible with the pre big August 15th update? If not I can always just edit the code myself (I think) for my static build. Might do that actually. lol.

If you actually [read the update notes ;p](https://github.com/Amorano/Jovimetrix?tab=readme-ov-file#updates) I list which versions of ComfyUI release and the frontend I support each time.

`Supports ComfyUI 0.2.1+, frontend 1.2.45+`

These are the most current ComfyUI release(s).

Cheers.

**Comment by christian-byrne** [comment] 2024-09-05 02:28
After updating to 090a32d:

- Chrome: Works (crashed on first load, then worked even after spam refreshing)
- Edge: Works mostly (only crashes after refreshing 20~ times consecutively)
- Opera: Works

There was also a chromium update that I installed today:

![Selection_311](https://github.com/user-attachments/assets/c3655cee-2932-4c84-8684-00ea0358e12f)

Nice work.

**Comment by Amorano** [comment] 2024-09-08 19:06
Going to mark this closed. Just comment if this pops up again.

**Closed by Amorano** 2024-09-08 19:06 UTC
